### PR TITLE
Add sqsbatch for easy sqs sending in batches

### PR DESCRIPTION
**Pull request by satyap**
Package sqsbatch helps us send batched messages to an SQS queue.
Use New() to get an SqsBatch object. Use the object's Add() method to add as many messages as you want.
The object will add them to the queue in batches of 10 (so that's 1 AWS API call every 10 messages).
After you are done adding messages, call Send() to finish sending the messages. (If you Add() 23 messages,
20 will get sent automatically in 2 batches, but you need an explicit Send() to send the last 3.)

### CODE REVIEW

**Comment by satyap** [comment]
As always, please let me know if anything needs improvement. Thanks!

**Comment by theherk** [comment]
Is there a reason to distinguish this from an `sqs` package? I'm not sure you wouldn't just have batch processing in that aide. There may be a technical reason (let me know), but if not I'd suggest making this the beginning of the sqs aide, rather than sqsbatch.

**Comment by satyap** [comment]
Makes sense, this could be the start of the `sqs` aide. Do you recommend a `SqsBatch` struct in `sqs` package, or `Batch*` prefixed funcs like `BatchSend`?

**Comment by satyap** [comment]
Looking at the struct, there are some batch-specific members, so it makes sense to me to have a SqsBatch inside the `sqs` package. Let me know if anyone else feels otherwise.

**Comment by satyap** [comment]
Hold off on this for a bit, I need to think about the testing interface.

**Comment by theherk** [comment]
Sure thing. Let me know when you open it back up. Seems like good functionality to have here.

**Comment by satyap** [comment]
Opened #16 because github won't let me open this PR for some reason.

**Pull request closed without merging**
